In [1]:
# get our db url
# create db engine via sqlalchemy

In [1]:
from env import config, BASE_DIR
from sqlalchemy import create_engine, text

In [2]:
DATABASE_URL = config("FLIGHT_PRICES_DATABASE_URL", cast=str, default=None)
DATABASE_URL is not None

True

In [3]:
engine = create_engine(str(DATABASE_URL))

In [4]:
DATASET_DIR = BASE_DIR / "datasets"
DATASET_DIR.exists()

True

In [5]:
FLIGHT_PRICES_CSV = DATASET_DIR / "itineraries-min-50k.csv"
FLIGHT_PRICES_CSV.exists()

True

In [6]:
import pandas as pd # dask

In [7]:
df = pd.read_csv(str(FLIGHT_PRICES_CSV))
df.head(n=10)

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0.0,False,False,...,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0.0,False,False,...,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0.0,False,False,...,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0.0,False,False,...,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0.0,False,False,...,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach
5,79eda9f841e226a1e2121d74211e595c,2022-04-16,2022-04-17,ATL,BOS,VH0AUEL1,PT2H38M,0.0,False,False,...,1650216180,2022-04-17T13:23:00.000-04:00,BOS,ATL,JetBlue Airways,B6,NaN,9480,947,coach
6,9335fae376c38bb61263281779f469ec,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT4H12M,0.0,False,False,...,1650203400||1650213120,2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Airbus A320,5400||7500,228||728,coach||coach
7,3904bf87f2d1daf334f1ae7e3b876028,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H18M,0.0,False,False,...,1650203400||1650217080,2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Boeing 737-800,5400||8280,228||728,coach||coach
8,d93988734c44a3c075d9efe373352507,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H32M,0.0,False,False,...,1650198060||1650213120,2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Airbus A320,4860||7500,228||728,coach||coach
9,562e7d5dd6ecbf1509c0c19711dbdca9,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT6H38M,0.0,False,False,...,1650198060||1650217080,2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Boeing 737-800,4860||8280,228||728,coach||coach

In [8]:
df.dtypes

legId                                 object
searchDate                            object
flightDate                            object
startingAirport                       object
destinationAirport                    object
fareBasisCode                         object
travelDuration                        object
elapsedDays                          float64
isBasicEconomy                          bool
isRefundable                            bool
isNonStop                               bool
baseFare                             float64
totalFare                            float64
seatsRemaining                       float64
totalTravelDistance                  float64
segmentsDepartureTimeEpochSeconds     object
segmentsDepartureTimeRaw              object
segmentsArrivalTimeEpochSeconds       object
segmentsArrivalTimeRaw                object
segmentsArrivalAirportCode            object
segmentsDepartureAirportCode          object
segmentsAirlineName                   object
segmentsAirlineCode                   object
segmentsEquipmentDescription          object
segmentsDurationInSeconds             object
segmentsDistance                      object
segmentsCabinCode                     object
dtype: object

In [62]:
df.destinationAirport.value_counts()

destinationAirport
LAX    4893
LGA    3912
DFW    3824
DEN    3704
MIA    3521
BOS    3437
ATL    3373
ORD    3279
DTW    3254
SFO    3184
CLT    2953
EWR    2570
PHL    2462
JFK    2271
IAD    1781
OAK    1582
Name: count, dtype: int64

In [9]:
df['flightDate'] = pd.to_datetime(df['flightDate'])

In [69]:
group_by_columns = ['flightDate', 'startingAirport', 'destinationAirport', 'isBasicEconomy', 'isRefundable', 'isNonStop', 'segmentsAirlineName']
target_column = 'totalFare'
desired_columns = group_by_columns + [target_column]
sub_df = df.copy()[desired_columns]
sub_df = sub_df.groupby(group_by_columns)[target_column].mean().reset_index()
sub_df['startingAirport'] = sub_df['startingAirport'].apply(lambda x: f"{x}".strip())
sub_df['destinationAirport'] = sub_df['destinationAirport'].apply(lambda x: f"{x}".strip())
sub_df['totalFare'] = sub_df['totalFare'].round(0).apply(lambda x: int(x))
sub_df.dropna(inplace=True)
sub_df.head(n=40)

,flightDate,startingAirport,destinationAirport,isBasicEconomy,isRefundable,isNonStop,segmentsAirlineName,totalFare
0,2022-04-17,ATL,BOS,False,False,False,American Airlines||American Airlines,273
1,2022-04-17,ATL,BOS,False,False,False,Spirit Airlines||Spirit Airlines,301
2,2022-04-17,ATL,BOS,False,False,False,United||United,352
3,2022-04-17,ATL,BOS,False,False,True,American Airlines,355
4,2022-04-17,ATL,BOS,False,False,True,Delta,307
5,2022-04-17,ATL,BOS,False,False,True,JetBlue Airways,302
6,2022-04-17,ATL,BOS,True,False,False,United||United,307
7,2022-04-17,ATL,CLT,False,False,False,American Airlines||American Airlines,492
8,2022-04-17,ATL,CLT,False,False,False,JetBlue Airways||JetBlue Airways,543
9,2022-04-17,ATL,CLT,False,False,False,United||United,467
10,2022-04-17,ATL,CLT,False,False,True,American Airlines,425
11,2022-04-17,ATL,CLT,False,False,True,Delta,399
12,2022-04-17,ATL,DEN,False,False,False,American Airlines||American Airlines,305
13,2022-04-17,ATL,DEN,False,False,False,Frontier Airlines||Frontier Airlines,554
14,2022-04-17,ATL,DEN,False,False,False,Spirit Airlines||Spirit Airlines,273
15,2022-04-17,ATL,DEN,False,False,False,United||United,320
16,2022-04-17,ATL,DEN,False,False,True,Delta,297
17,2022-04-17,ATL,DEN,False,False,True,Frontier Airlines,134
18,2022-04-17,ATL,DEN,False,False,True,United,297
19,2022-04-17,ATL,DFW,False,False,False,American Airlines||American Airlines,211
20,2022-04-17,ATL,DFW,False,False,False,Spirit Airlines||Spirit Airlines,344
21,2022-04-17,ATL,DFW,False,False,False,United||United,227
22,2022-04-17,ATL,DFW,False,False,True,American Airlines,212
23,2022-04-17,ATL,DFW,False,False,True,Delta,224
24,2022-04-17,ATL,DFW,False,False,True,Frontier Airlines,404
25,2022-04-17,ATL,DFW,False,False,True,Spirit Airlines,169
26,2022-04-17,ATL,DTW,False,False,False,American Airlines||American Airlines,250
27,2022-04-17,ATL,DTW,False,False,False,Delta||Cape Air||Cape Air||Delta,788
28,2022-04-17,ATL,DTW,False,False,False,Delta||Delta,568
29,2022-04-17,ATL,DTW,False,False,False,Delta||United,432
30,2022-04-17,ATL,DTW,False,False,False,JetBlue Airways||JetBlue Airways,314
31,2022-04-17,ATL,DTW,False,False,False,Spirit Airlines||Spirit Airlines,312
32,2022-04-17,ATL,DTW,False,False,False,United||United,284
33,2022-04-17,ATL,DTW,False,False,True,Delta,499
34,2022-04-17,ATL,DTW,False,False,True,Spirit Airlines,166
35,2022-04-17,ATL,EWR,False,False,False,American Airlines||American Airlines,237
36,2022-04-17,ATL,EWR,False,False,False,Spirit Airlines||Spirit Airlines,372
37,2022-04-17,ATL,EWR,False,False,False,United||United,263
38,2022-04-17,ATL,EWR,False,False,True,American Airlines,229
39,2022-04-17,ATL,EWR,False,False,True,Delta,220

In [70]:
sub_df.dtypes

flightDate             datetime64[ns]
startingAirport                object
destinationAirport             object
isBasicEconomy                   bool
isRefundable                     bool
isNonStop                        bool
segmentsAirlineName            object
totalFare                       int64
dtype: object

In [71]:
out_df = sub_df.copy()

In [72]:
table_name = "flight_prices"
out_df.to_sql(table_name, engine, if_exists='replace', index=False)

9592

In [73]:
rows, cols = out_df.shape
rows, cols

(9592, 8)

In [74]:
with engine.connect() as conn:
    results = conn.execute(text(f"SELECT * from {table_name} LIMIT 10"))
    print(results.all())

[(datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 0, 'American Airlines||American Airlines', 273), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 0, 'Spirit Airlines||Spirit Airlines', 301), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 0, 'United||United', 352), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 1, 'American Airlines', 355), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 1, 'Delta', 307), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 0, 0, 1, 'JetBlue Airways', 302), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'BOS', 1, 0, 0, 'United||United', 307), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'CLT', 0, 0, 0, 'American Airlines||American Airlines', 492), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'CLT', 0, 0, 0, 'JetBlue Airways||JetBlue Airways', 543), (datetime.datetime(2022, 4, 17, 0, 0), 'ATL', 'CLT', 0, 0, 0, 'United||United', 467)]